### ISSUE TITLE
openshift-ansible uses a tag of docker.io/ansibleplaybookbundle/ansible-service-broker that does not exist.

### ISSUE THREAD

**Issue by ozdanborne** [openshift/openshift-ansible#6435]
#### Description

My fresh v3.7 cluster is provisioning successfully but the `openshift-ansible-service-broker` pod is stuck in `ErrImagePull`.

```
  containerStatuses:
  - image: ansibleplaybookbundle/ansible-service-broker:latest
    imageID: ""
    lastState: {}
    name: asb
    ready: false
    restartCount: 0
    state:
      waiting:
        message: 'rpc error: code = 2 desc = Tag latest not found in repository docker.io/ansibleplaybookbundle/ansible-service-broker'
        reason: ErrImagePull
```
Seems that by default (https://github.com/openshift/openshift-ansible/blob/master/roles/ansible_service_broker/vars/default_images.yml#L4) they use the tag `latest` which doesn't exist on dockerhub: https://hub.docker.com/r/ansibleplaybookbundle/ansible-service-broker/tags/

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`: 

If you're operating from a **git clone**:

* The output of `git describe`: 

Place the output between the code block below:

```
ansible 2.4.2.0
openshift-ansible-3.4.17-1-4257-g8e4c88a
```

##### Steps To Reproduce

Will have to find time later to give more information than that. Mostly I'm stunned that I'm the only one hitting this...

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
CentOS Linux release 7.4.1708 (Core) 

```

**Comment by milad-soufastai** [comment]
I see the same behavior on my fresh 3.7 install.

**Comment by fabianvf** [comment]
Actually that's pulling the wrong image entirely... It should be pointing at ansibleplaybookbundle/origin-ansible-service-broker instead. As a workaround, you can set the variable `ansible_service_broker_image_prefix` to `ansibleplaybookbundle/origin-`, and I'll get a fix for this in ASAP.

**Comment by jeffrey4l** [comment]
Get follow errors after use @fabianvf solution

```
# oc -n openshift-ansible-service-broker  logs asb-2-lw2pl
[2018-01-08T16:14:56.851Z] [INFO] - Broker configured to bootstrap on startup
[2018-01-08T16:14:56.851Z] [INFO] - Attempting bootstrap...
[2018-01-08T16:14:56.851Z] [INFO] - AnsibleBroker::Bootstrap
!!!!!!filter mode is none[2018-01-08T16:14:59.328Z] [INFO] - Validating specs...
[2018-01-08T16:14:59.328Z] [NOTICE] - All specs passed validation!
!!!!!!filter mode is none[2018-01-08T16:15:00.885Z] [INFO] - Validating specs...
[2018-01-08T16:15:00.885Z] [NOTICE] - All specs passed validation!
!!!!!!filter mode is none[2018-01-08T16:15:01.069Z] [INFO] - Validating specs...
[2018-01-08T16:15:01.069Z] [NOTICE] - All specs passed validation!
!!!!!!filter mode is none[2018-01-08T16:15:01.236Z] [INFO] - Validating specs...
[2018-01-08T16:15:01.236Z] [NOTICE] - All specs passed validation!
[2018-01-08T16:15:01.236Z] [NOTICE] - Broker successfully bootstrapped on startup
[2018-01-08T16:15:01.707Z] [ERROR] - Unable to retrieve cluster roles rules from cluster
 You must be using OpenShift 3.7 to use the User rules check.
the server could not find the requested resource

```

**Comment by fabianvf** [comment]
@shawn-hurley do you recognize this?

**Comment by shawn-hurley** [comment]
That fix is being built for latest today. 

The bug was merged here: https://github.com/openshift/ansible-service-broker/pull/618 

You can test this by using the canary tag but as previously stated we are releasing a new latest today that should fix this problem.

**Comment by jeffrey4l** [comment]
cool, thanks guys.

**Comment by maverick85** [comment]
This issue is still happening. There are several issues open about it.

Right now using fix by adding to inventory file:
```
ansible_service_broker_image=docker.io/ansibleplaybookbundle/origin-ansible-service-broker:ansible-service-broker-1.2.17-1
ansible_service_broker_local_registry_whitelist=['.*']
```

I don't know why this issues look abandoned in 2019. I am using a simple inventory file and I am encountering a number of open issues, some have been closed like ansible-service-broker#618 but the issue is easily replicable.

**Comment by alebeta90** [comment]
Yes as @maverick85 said, this issue is still alive. So far the ASB service is not working properly.

In my case we are running Origin v3.11
